/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as CheckoutTierRouteImport } from './routes/checkout.$tier'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountPlanRouteImport } from './routes/account.plan'
import { Route as AccountHistoryRouteImport } from './routes/account.history'
import { Route as AccountConnectionsRouteImport } from './routes/account.connections'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const CheckoutTierRoute = CheckoutTierRouteImport.update({
  id: '/checkout/$tier',
  path: '/checkout/$tier',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPlanRoute = AccountPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AccountRoute,
} as any)
const AccountHistoryRoute = AccountHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AccountRoute,
} as any)
const AccountConnectionsRoute = AccountConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/account/connections': typeof AccountConnectionsRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/plan': typeof AccountPlanRoute
  '/account/profile': typeof AccountProfileRoute
  '/checkout/$tier': typeof CheckoutTierRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/account/connections': typeof AccountConnectionsRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/plan': typeof AccountPlanRoute
  '/account/profile': typeof AccountProfileRoute
  '/checkout/$tier': typeof CheckoutTierRoute
  '/account': typeof AccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/account/connections': typeof AccountConnectionsRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/plan': typeof AccountPlanRoute
  '/account/profile': typeof AccountProfileRoute
  '/checkout/$tier': typeof CheckoutTierRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/signup'
    | '/account/connections'
    | '/account/history'
    | '/account/plan'
    | '/account/profile'
    | '/checkout/$tier'
    | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/signup'
    | '/account/connections'
    | '/account/history'
    | '/account/plan'
    | '/account/profile'
    | '/checkout/$tier'
    | '/account'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/signup'
    | '/account/connections'
    | '/account/history'
    | '/account/plan'
    | '/account/profile'
    | '/checkout/$tier'
    | '/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AppRoute: typeof AppRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  CheckoutTierRoute: typeof CheckoutTierRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/checkout/$tier': {
      id: '/checkout/$tier'
      path: '/checkout/$tier'
      fullPath: '/checkout/$tier'
      preLoaderRoute: typeof CheckoutTierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/plan': {
      id: '/account/plan'
      path: '/plan'
      fullPath: '/account/plan'
      preLoaderRoute: typeof AccountPlanRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/history': {
      id: '/account/history'
      path: '/history'
      fullPath: '/account/history'
      preLoaderRoute: typeof AccountHistoryRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/connections': {
      id: '/account/connections'
      path: '/connections'
      fullPath: '/account/connections'
      preLoaderRoute: typeof AccountConnectionsRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountConnectionsRoute: typeof AccountConnectionsRoute
  AccountHistoryRoute: typeof AccountHistoryRoute
  AccountPlanRoute: typeof AccountPlanRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountConnectionsRoute: AccountConnectionsRoute,
  AccountHistoryRoute: AccountHistoryRoute,
  AccountPlanRoute: AccountPlanRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AppRoute: AppRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  CheckoutTierRoute: CheckoutTierRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
